run:
  tests: false

linters-settings:
  govet:
    check-shadowing: false
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - deadcode
    - unused
    - errcheck
    - dupl
    - gocyclo

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - staticcheck
        - gosec
      text: "SA1012:"

    - linters:
        - gosec
      text: "G201:"
    - linters:
        - gosec
      text: "G304:"
    - linters:
        - gosec
      text: "G107:"
