version: 2.1
executors:
  golang:
    docker:
      - image: circleci/golang:1.12.6
jobs:
  lint:
    executor: golang
    steps:
      - checkout
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
      - run: golangci-lint run --deadline 5m ./...
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install golang
          command: |
            sudo rm -rf /usr/local/go
            sudo rm -rf $(echo $GOPATH)
            curl -O https://storage.googleapis.com/golang/go1.12.7.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.12.7.linux-amd64.tar.gz
            export GOPATH=$HOME/.go
            export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
      - run: go get -v -d ./...
      - run: go test -v -race ./...
workflows:
  version: 2
  release:
    jobs:
      - lint
      - test:
          requires:
            - lint
